# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stkAssembled',
            fields=[
                ('assembledid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'stkAssembled',
            },
        ),
        migrations.CreateModel(
            name='stkBrandMaster',
            fields=[
                ('brandid', models.AutoField(primary_key=True, serialize=False)),
                ('brandname', models.CharField(max_length=50)),
                ('brandcode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stkBrandMaster',
            },
        ),
        migrations.CreateModel(
            name='stkCompanyMaster',
            fields=[
                ('firmid', models.AutoField(primary_key=True, serialize=False)),
                ('firmname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stkCompanyMaster',
            },
        ),
        migrations.CreateModel(
            name='stkDept',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'stkDept',
            },
        ),
        migrations.CreateModel(
            name='stkFirmAccess',
            fields=[
                ('empcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('firmid', models.ForeignKey(db_column='firmid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkCompanyMaster')),
            ],
            options={
                'db_table': 'stkFirmAccess',
            },
        ),
        migrations.CreateModel(
            name='stkIssue',
            fields=[
                ('issueid', models.AutoField(primary_key=True, serialize=False)),
                ('issuedate', models.DateField(null=True)),
                ('issuedqty', models.IntegerField(default=1, null=True)),
                ('issuedbyid', models.CharField(max_length=20, null=True)),
                ('issueddeptid', models.ForeignKey(db_column='deptid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkDept')),
            ],
            options={
                'db_table': 'stkIssue',
            },
        ),
        migrations.CreateModel(
            name='stkIssueDetails',
            fields=[
                ('issuedetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('latestissue', models.CharField(default=1, max_length=2)),
                ('issueid', models.ForeignKey(db_column='issueid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkIssue')),
            ],
            options={
                'db_table': 'stkIssueDetails',
            },
        ),
        migrations.CreateModel(
            name='stkItemDetails',
            fields=[
                ('itemdetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('health', models.CharField(default='G', max_length=4)),
                ('currentstatus', models.CharField(default='arrived', max_length=30)),
                ('assembledstatus', models.CharField(default='N', max_length=3)),
                ('manualentered', models.CharField(default='N', max_length=3)),
                ('existing', models.CharField(default='N', max_length=3)),
                ('serialno', models.CharField(max_length=60, null=True)),
                ('fisatid', models.CharField(max_length=100)),
                ('itemoutgoingstatus', models.CharField(default='N', max_length=3)),
                ('issuedornot', models.CharField(default='N', max_length=3)),
                ('installedornot', models.CharField(default='N', max_length=3)),
                ('returnedfromdept', models.IntegerField(default=0)),
                ('interval', models.IntegerField(default=1)),
                ('chargeofitemid', models.CharField(max_length=20, null=True)),
                ('assembledid', models.ForeignKey(db_column='assembledid', null=True, on_delete=django.db.models.deletion.CASCADE, to='stk.stkAssembled')),
                ('deptid', models.ForeignKey(db_column='deptid', null=True, on_delete=django.db.models.deletion.CASCADE, to='stk.stkDept')),
                ('firmid', models.ForeignKey(db_column='firmid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkCompanyMaster')),
                ('issueid', models.ForeignKey(db_column='issueid', null=True, on_delete=django.db.models.deletion.CASCADE, to='stk.stkIssue')),
            ],
            options={
                'db_table': 'stkItemDetails',
            },
        ),
        migrations.CreateModel(
            name='stkItemMaster',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('qtyavailable', models.IntegerField(default=0)),
                ('existingqty', models.IntegerField(default=25)),
                ('totalnoofcontents', models.IntegerField(default=0, null=True)),
                ('whethersubitem', models.CharField(default='N', max_length=5)),
                ('itemcode', models.CharField(default='N', max_length=40)),
                ('brandid', models.ForeignKey(db_column='brandid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkBrandMaster')),
                ('firmid', models.ForeignKey(db_column='firmid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkCompanyMaster')),
            ],
            options={
                'db_table': 'stkItemMaster',
            },
        ),
        migrations.CreateModel(
            name='stkLocation',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField(max_length=50)),
                ('deptid', models.ForeignKey(db_column='deptid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkDept')),
            ],
            options={
                'db_table': 'stkLocation',
            },
        ),
        migrations.CreateModel(
            name='stkLogintab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stkLogintab',
            },
        ),
        migrations.CreateModel(
            name='stkMainCategory',
            fields=[
                ('maincatid', models.AutoField(primary_key=True, serialize=False)),
                ('maincatname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stkMainCategory',
            },
        ),
        migrations.CreateModel(
            name='stkModelMaster',
            fields=[
                ('modelid', models.AutoField(primary_key=True, serialize=False)),
                ('modelname', models.CharField(max_length=50)),
                ('specification', models.CharField(max_length=50)),
                ('productinfo', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('qtyavailable', models.IntegerField(default=0)),
                ('modelcode', models.CharField(max_length=50)),
                ('brandid', models.ForeignKey(db_column='brandid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkBrandMaster')),
            ],
            options={
                'db_table': 'stkModelMaster',
            },
        ),
        migrations.CreateModel(
            name='stkOutgoing',
            fields=[
                ('itemoutgoingid', models.AutoField(primary_key=True, serialize=False)),
                ('datedispatch', models.DateField()),
                ('datereturn', models.DateField(null=True)),
                ('remarks', models.CharField(max_length=80)),
                ('itemsenderid', models.CharField(max_length=20)),
                ('itemreceiverid', models.CharField(max_length=20, null=True)),
                ('currentstatus', models.CharField(default='G', max_length=4)),
                ('oldhealthstatus', models.CharField(default='G', max_length=4)),
                ('oldoriginalstatus', models.CharField(default='arrived', max_length=30)),
            ],
            options={
                'db_table': 'stkOutgoing',
            },
        ),
        migrations.CreateModel(
            name='stkPrivilegeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.IntegerField(default=0)),
                ('edit', models.IntegerField(default=0)),
                ('delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stkPrivilegeDescription',
            },
        ),
        migrations.CreateModel(
            name='stkPrivilegeGroup',
            fields=[
                ('groupid', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stkPrivilegeGroup',
            },
        ),
        migrations.CreateModel(
            name='stkPurchaseInfo',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('individualdiscount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('individualtaxpercentage', models.IntegerField(default=0)),
                ('individualtaxamount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stkregtrpageno', models.IntegerField(default=0)),
                ('purchasereturnstatus', models.CharField(default='N', max_length=3)),
                ('purchasereturnqty', models.IntegerField(default=0)),
                ('itemid', models.ForeignKey(db_column='itemid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkItemMaster')),
                ('maincatid', models.ForeignKey(db_column='maincatid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkMainCategory')),
            ],
            options={
                'db_table': 'stkPurchaseInfo',
            },
        ),
        migrations.CreateModel(
            name='stkPurchaseMaster',
            fields=[
                ('purchaseid', models.AutoField(primary_key=True, serialize=False)),
                ('totprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tottax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('netamount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('totdiscount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoiceno', models.IntegerField(default=0)),
                ('invoicedate', models.DateField()),
                ('purchasedate', models.DateField()),
                ('entereddate', models.DateField()),
                ('enteredbyid', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'stkPurchaseMaster',
            },
        ),
        migrations.CreateModel(
            name='stkPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refno', models.IntegerField(default=0)),
                ('quotid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stkPurchaseOrder',
            },
        ),
        migrations.CreateModel(
            name='stkPurchaseReturn',
            fields=[
                ('purchasereturnid', models.AutoField(primary_key=True, serialize=False)),
                ('returneddate', models.DateField()),
                ('returnedbyid', models.CharField(max_length=30)),
                ('enteredbyid', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100, null=True)),
                ('itemdetailsid', models.ForeignKey(db_column='itemdetailsid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkItemDetails')),
                ('maincatid', models.ForeignKey(db_column='maincatid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkMainCategory')),
                ('purchaseid', models.ForeignKey(db_column='purchaseid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkPurchaseMaster')),
            ],
            options={
                'db_table': 'stkPurchaseReturn',
            },
        ),
        migrations.CreateModel(
            name='stkPurchaseReturnDetails',
            fields=[
                ('purchasereturndetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('purchasereturnid', models.ForeignKey(db_column='purchasereturnid', null=True, on_delete=django.db.models.deletion.CASCADE, to='stk.stkPurchaseReturn')),
                ('recordid', models.ForeignKey(db_column='recordid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkPurchaseInfo')),
            ],
            options={
                'db_table': 'stkPurchaseReturnDetails',
            },
        ),
        migrations.CreateModel(
            name='stkReturnFromDept',
            fields=[
                ('returnid', models.AutoField(primary_key=True, serialize=False)),
                ('returndate', models.DateField()),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('enteredbyid', models.ForeignKey(db_column='enteredbyid', on_delete=django.db.models.deletion.CASCADE, related_name='stkreturnfromdept_enteredbyid', to='stk.stkFirmAccess')),
                ('fromdeptid', models.ForeignKey(db_column='fromdeptid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkDept')),
                ('fromlocationid', models.ForeignKey(db_column='fromlocationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='stk.stkLocation')),
                ('issuedetailsid', models.ForeignKey(db_column='issuedetailsid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkIssueDetails')),
                ('itemdetailsid', models.ForeignKey(db_column='itemdetailsid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkItemDetails')),
                ('returnedbyid', models.ForeignKey(db_column='returnedbyid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkFirmAccess')),
            ],
            options={
                'db_table': 'stkReturnFromDept',
            },
        ),
        migrations.CreateModel(
            name='stkServiceCompany',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=50)),
                ('mailid', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stkServiceCompany',
            },
        ),
        migrations.CreateModel(
            name='stkStoreMaster',
            fields=[
                ('storeid', models.AutoField(primary_key=True, serialize=False)),
                ('mainstorename', models.CharField(max_length=50)),
                ('underwhichstore', models.IntegerField(default=0)),
                ('firmid', models.ForeignKey(db_column='firmid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkCompanyMaster')),
            ],
            options={
                'db_table': 'stkStoreMaster',
            },
        ),
        migrations.CreateModel(
            name='stkSubCategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('subcatname', models.CharField(max_length=50)),
                ('lastvalue', models.IntegerField(default=0)),
                ('maincatid', models.ForeignKey(db_column='maincatid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkMainCategory')),
            ],
            options={
                'db_table': 'stkSubCategory',
            },
        ),
        migrations.CreateModel(
            name='stkSupplier',
            fields=[
                ('supplierid', models.AutoField(primary_key=True, serialize=False)),
                ('suppliername', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('mailid', models.CharField(max_length=50)),
                ('mobileorlandline', models.CharField(max_length=15)),
                ('vatno', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=75)),
            ],
            options={
                'db_table': 'stkSupplier',
            },
        ),
        migrations.CreateModel(
            name='stkUnits',
            fields=[
                ('unitid', models.AutoField(primary_key=True, serialize=False)),
                ('unitname', models.CharField(max_length=50)),
                ('noofcontentsifany', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'stkUnits',
            },
        ),
        migrations.CreateModel(
            name='stkWarrantyOrAmc',
            fields=[
                ('warrantyoramcid', models.AutoField(primary_key=True, serialize=False)),
                ('warrantyfrom', models.DateField()),
                ('warrantyto', models.DateField()),
                ('woramc', models.CharField(default='W', max_length=4)),
                ('itemdetailsid', models.ForeignKey(db_column='itemdetailsid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkItemDetails')),
            ],
            options={
                'db_table': 'stkWarrantyOrAmc',
            },
        ),
        migrations.AddField(
            model_name='stkpurchasemaster',
            name='supplierid',
            field=models.ForeignKey(db_column='supplierid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkSupplier'),
        ),
        migrations.AddField(
            model_name='stkpurchaseinfo',
            name='purchaseid',
            field=models.ForeignKey(db_column='purchaseid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkPurchaseMaster'),
        ),
        migrations.AddField(
            model_name='stkpurchaseinfo',
            name='unitid',
            field=models.ForeignKey(db_column='unitid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkUnits'),
        ),
        migrations.AddField(
            model_name='stkprivilegegroup',
            name='storeid',
            field=models.ForeignKey(db_column='storeid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkStoreMaster'),
        ),
        migrations.AddField(
            model_name='stkprivilegedescription',
            name='groupid',
            field=models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkPrivilegeGroup'),
        ),
        migrations.AddField(
            model_name='stkoutgoing',
            name='companyid',
            field=models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkServiceCompany'),
        ),
        migrations.AddField(
            model_name='stkoutgoing',
            name='itemdetailsid',
            field=models.ForeignKey(db_column='itemdetailsid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkItemDetails'),
        ),
        migrations.AddField(
            model_name='stkmodelmaster',
            name='subcatid',
            field=models.ForeignKey(db_column='subcatid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkSubCategory'),
        ),
        migrations.AddField(
            model_name='stkmodelmaster',
            name='unitid',
            field=models.ForeignKey(db_column='unitid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkUnits'),
        ),
        migrations.AddField(
            model_name='stklogintab',
            name='groupid',
            field=models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkPrivilegeGroup'),
        ),
        migrations.AddField(
            model_name='stkitemmaster',
            name='maincatid',
            field=models.ForeignKey(db_column='maincatid', default=1, on_delete=django.db.models.deletion.CASCADE, to='stk.stkMainCategory'),
        ),
        migrations.AddField(
            model_name='stkitemmaster',
            name='modelid',
            field=models.ForeignKey(db_column='modelid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkModelMaster'),
        ),
        migrations.AddField(
            model_name='stkitemmaster',
            name='storeid',
            field=models.ForeignKey(db_column='storeid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkStoreMaster'),
        ),
        migrations.AddField(
            model_name='stkitemmaster',
            name='subcatid',
            field=models.ForeignKey(db_column='subcatid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkSubCategory'),
        ),
        migrations.AddField(
            model_name='stkitemmaster',
            name='unitid',
            field=models.ForeignKey(db_column='unitid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkUnits'),
        ),
        migrations.AddField(
            model_name='stkitemdetails',
            name='itemid',
            field=models.ForeignKey(db_column='itemid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkItemMaster'),
        ),
        migrations.AddField(
            model_name='stkitemdetails',
            name='itemoutgoingid',
            field=models.ForeignKey(db_column='itemoutgoingid', null=True, on_delete=django.db.models.deletion.CASCADE, to='stk.stkOutgoing'),
        ),
        migrations.AddField(
            model_name='stkitemdetails',
            name='locationid',
            field=models.ForeignKey(db_column='locationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='stk.stkLocation'),
        ),
        migrations.AddField(
            model_name='stkitemdetails',
            name='purchaseid',
            field=models.ForeignKey(db_column='purchaseid', null=True, on_delete=django.db.models.deletion.CASCADE, to='stk.stkPurchaseMaster'),
        ),
        migrations.AddField(
            model_name='stkitemdetails',
            name='purchasereturnid',
            field=models.ForeignKey(db_column='purchasereturnid', null=True, on_delete=django.db.models.deletion.CASCADE, to='stk.stkPurchaseReturn'),
        ),
        migrations.AddField(
            model_name='stkitemdetails',
            name='storeid',
            field=models.ForeignKey(db_column='storeid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkStoreMaster'),
        ),
        migrations.AddField(
            model_name='stkitemdetails',
            name='warrantyoramcid',
            field=models.ForeignKey(db_column='warrantyoramcid', null=True, on_delete=django.db.models.deletion.CASCADE, to='stk.stkWarrantyOrAmc'),
        ),
        migrations.AddField(
            model_name='stkissuedetails',
            name='itemdetailsid',
            field=models.ForeignKey(db_column='itemdetailsid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkItemDetails'),
        ),
        migrations.AddField(
            model_name='stkissue',
            name='maincatid',
            field=models.ForeignKey(db_column='maincatid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkMainCategory'),
        ),
        migrations.AddField(
            model_name='stkissue',
            name='unitid',
            field=models.ForeignKey(db_column='unitid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkUnits'),
        ),
        migrations.AddField(
            model_name='stkdept',
            name='storeid',
            field=models.ForeignKey(db_column='storeid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkStoreMaster'),
        ),
        migrations.AddField(
            model_name='stkassembled',
            name='mainitemid',
            field=models.ForeignKey(db_column='mainitemid', on_delete=django.db.models.deletion.CASCADE, related_name='stkassembled_mainitemid', to='stk.stkItemMaster'),
        ),
        migrations.AddField(
            model_name='stkassembled',
            name='subitemid',
            field=models.ForeignKey(db_column='subitemid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkItemMaster'),
        ),
    ]
