# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stkOutgoings',
            fields=[
                ('itemoutgoingid', models.AutoField(primary_key=True, serialize=False)),
                ('datedispatch', models.DateField()),
                ('datereturn', models.DateField(null=True)),
                ('remarks', models.CharField(max_length=80)),
                ('itemsenderid', models.CharField(max_length=20)),
                ('itemreceiverid', models.CharField(max_length=20, null=True)),
                ('currentstatus', models.CharField(default='G', max_length=4)),
                ('oldhealthstatus', models.CharField(default='G', max_length=4)),
                ('oldoriginalstatus', models.CharField(default='arrived', max_length=30)),
                ('companyid', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkServiceCompany')),
                ('itemdetailsid', models.ForeignKey(db_column='itemdetailsid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkItemDetails')),
            ],
            options={
                'db_table': 'stkOutgoings',
            },
        ),
    ]
