# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0003_auto_20170722_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stkoutgoing',
            name='companyid',
        ),
        migrations.RemoveField(
            model_name='stkoutgoing',
            name='itemdetailsid',
        ),
        migrations.DeleteModel(
            name='stkOutgoing',
        ),
    ]
