# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0004_auto_20170722_0515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stkOutgoings',
            new_name='stkOutgoing',
        ),
        migrations.AlterModelTable(
            name='stkoutgoing',
            table='stkOutgoing',
        ),
    ]
