# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0005_auto_20170722_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='stkCurrentStatus',
            fields=[
                ('currentstatusid', models.AutoField(primary_key=True, serialize=False)),
                ('currentstatusvalue', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'stkCurrentStatus',
            },
        ),
        migrations.CreateModel(
            name='stkHealthStatus',
            fields=[
                ('healthstatusid', models.AutoField(primary_key=True, serialize=False)),
                ('healthstatusvalue', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'stkHealthStatus',
            },
        ),
    ]
