# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0006_stkcurrentstatus_stkhealthstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkitemdetails',
            name='currentstatusid',
            field=models.ForeignKey(db_column='currentstatusid', default=1, on_delete=django.db.models.deletion.CASCADE, to='stk.stkCurrentStatus'),
        ),
    ]
