# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0008_stkoutgoing_oldoriginalstatusid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkitemdetails',
            name='healthid',
            field=models.ForeignKey(db_column='oldhealthstatusid', default=1, on_delete=django.db.models.deletion.CASCADE, to='stk.stkHealthStatus'),
        ),
        migrations.AddField(
            model_name='stkoutgoing',
            name='oldhealthstatusid',
            field=models.ForeignKey(db_column='oldhealthstatusid', default=1, on_delete=django.db.models.deletion.CASCADE, to='stk.stkHealthStatus'),
        ),
    ]
