# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0009_auto_20170724_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkoutgoing',
            name='currentstatusid',
            field=models.ForeignKey(db_column='currentstatusid', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stkoutgoing_currentstatusid', to='stk.stkHealthStatus'),
        ),
    ]
