# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0010_stkoutgoing_currentstatusid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkitemdetails',
            name='healthid',
            field=models.ForeignKey(db_column='healthid', default=1, on_delete=django.db.models.deletion.CASCADE, to='stk.stkHealthStatus'),
        ),
    ]
