# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0011_auto_20170724_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stkitemdetails',
            name='currentstatus',
        ),
        migrations.RemoveField(
            model_name='stkitemdetails',
            name='health',
        ),
        migrations.RemoveField(
            model_name='stkoutgoing',
            name='currentstatus',
        ),
        migrations.RemoveField(
            model_name='stkoutgoing',
            name='oldhealthstatus',
        ),
        migrations.RemoveField(
            model_name='stkoutgoing',
            name='oldoriginalstatus',
        ),
    ]
