# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0012_auto_20170724_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='stkSampleUpload',
            fields=[
                ('returnid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mark', models.IntegerField()),
            ],
            options={
                'db_table': 'stkSampleUpload',
            },
        ),
    ]
