# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-26 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0013_stksampleupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='stkBreakdown',
            fields=[
                ('breakdownid', models.AutoField(primary_key=True, serialize=False)),
                ('maintenancedetails', models.CharField(max_length=100, null=True)),
                ('rdam', models.DateField(null=True)),
                ('technicianname', models.CharField(max_length=100)),
                ('complaints', models.CharField(max_length=50)),
                ('companyid', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkServiceCompany')),
                ('itemdetailsid', models.ForeignKey(db_column='itemdetailsid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkItemDetails')),
                ('itemoutgoingid', models.ForeignKey(db_column='itemoutgoingid', on_delete=django.db.models.deletion.CASCADE, to='stk.stkOutgoing')),
            ],
            options={
                'db_table': 'stkBreakdown',
            },
        ),
    ]
