# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizattended',
            fields=[
                ('quizid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.QuizLogin')),
            ],
        ),
        migrations.CreateModel(
            name='Quizdetails',
            fields=[
                ('quizdetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('answeredoption', models.CharField(max_length=30, null=True)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Question')),
                ('quizid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Quizattended')),
            ],
        ),
    ]
