# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_quizattended_quizdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizdetails',
            name='answeredoption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
