# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_auto_20170811_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattended',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
