# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_quizattended_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattended',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
