# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_auto_20170814_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattended',
            name='score',
            field=models.IntegerField(),
        ),
    ]
